### ISSUE TITLE
coda-7.1.0: assumes lwp is in PKG_CONFIG_PATH (bootstrap failure)

### ISSUE THREAD

**Issue by danielrobbins** [cmusatyalab/coda#105]
When bootstrapping and building coda-7.1.0, rpc2's configure script is run during bootstrap and a configure check runs which looks for lwp. But lwp may not be built or installed yet, and in this case (on a fresh build on a system without lwp installed,) this configure check will fail as follows:

```checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for cp... cp -f
checking for x86_64-pc-linux-gnu-pkg-config... /usr/bin/x86_64-pc-linux-gnu-pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for LWP... no
configure: error: Package requirements (lwp) were not met:

Package 'lwp', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables LWP_CFLAGS
and LWP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
configure: error: ./configure failed for lib-src/rpc2
```
Ideally, the configure script should understand that we are building a series of dependencies and lwp should be able to be found by rpc2 when it builds, so the bootstrap will 'just work'.

**Comment by danielrobbins** [comment]
I can temporarily workaround this issue as follows. First, install a standalone version of lwp. Then, perform bootstrap and compile of coda. Then remove standalone lwp. Then install coda (which will include its version of lwp.)

**Comment by jaharkes** [comment]
Not sure what your build environment is because there really isn't a standalone version of lwp. As there were no 3rd party users, and to avoid these kinds of issues with which library we're building/linking with we moved the lwp, rpc2 and rvm source into the main Coda source tree. Some of the issues we've seen before that were RPC2 built with one version of LWP, while Coda was built against a that RPC2 version, but with a different LWP library and the final executable linking in two different LWP releases, sometimes build with different and incompatible build options (coroutines vs. pthreads).

I tried to set it up so that everything will build against the in-tree version of LWP, ignoring whatever may be already installed on the system.

**Comment by danielrobbins** [comment]
Yes, I understand that lwp is now part of coda.

I had an older version of lwp before it was merged into coda which I was able to merge to satisfy the dependency. Coda built fine with this older version of lwp. As I stated, if you don't have lwp installed, then it is not picking up the bundled lwp that is now in the coda sources.

If you already had a previous version of coda installed on the system, then lwp is already installed too, and thus coda builds fine. If you start on a 'virgin' system with no lwp, I see a build failure as indicated in the bug report. I hope that makes sense.

**Comment by jaharkes** [comment]
I build in 'virgin' docker containers all the time, there is CI from a gitlab installation on every commit, and when I package a release all the packages are build in a pristine environment to avoid dependency issues.

It must be something else that was causing the build to fail.

**Comment by danielrobbins** [comment]
I ran the build by hand rather than in a Gentoo ebuild and it worked fine. I tracked down the issue to the fact that having PKG_CONFIG_PATH pre-set in the environment (which is done by default in Gentoo) wipes out the PKG_CONFIG_PATH setting for rvm so it cannot find lwp. If I do an "unset PKG_CONFIG_PATH" prior to running configure, configure completes without error. Having PKG_CONFIG_PATH set to a value shouldn't cause the configure script to fail, but since I have a simple workaround, I will leave it to you as to whether you want to fix this in your build scripts.

**Comment by jaharkes** [comment]
Thank you for digging into that and figuring it out. I just checked the configure macro where we change the PKG_CONFIG_PATH to include the sub-project directories and it looks like we only modify it when the variable is not already defined, not sure why.

I'll have to test it, but I think you really found a bug in the CODA_CONFIG_SUBDIRS macro in `configs/coda_macros.m4` and we should modify the search path even if it was already defined.

**Comment by stephenrkell** [comment]
For what it's worth, I ran into this issue and worked around it with the following patch (probably not the ideal fix, and do excuse my ranty comments-to-self).

```
diff --git a/configs/coda_macros.m4 b/configs/coda_macros.m4
index 09683ab..e37c608 100644
--- a/configs/coda_macros.m4
+++ b/configs/coda_macros.m4
@@ -2,7 +2,7 @@ dnl Macro to run configure on subprojects before continuing. This way we are
 dnl assured that generated files like uninstalled pkg-config files are
 dnl present. We also extend the pkg-config search path to look in the
 dnl sub-project directories.
-AC_DEFUN([CODA_CONFIG_SUBDIRS],
+AC_DEFUN([CODA_CONFIG_PKG_SUBDIRS],
   [if test -z "${PKG_CONFIG_PATH}" ; then
      PKG_CONFIG_PATH="${libdir}/pkgconfig:/usr/local/lib/pkgconfig"
    fi
@@ -12,7 +12,9 @@ AC_DEFUN([CODA_CONFIG_SUBDIRS],
    done
    PKG_CONFIG_PATH="${pc_pfx}${PKG_CONFIG_PATH}"
    export PKG_CONFIG_PATH
-   _AC_OUTPUT_SUBDIRS()
+   ])
+AC_DEFUN([CODA_CONFIG_SUBDIRS],
+  [_AC_OUTPUT_SUBDIRS()
    no_recursion=yes])
 
 dnl Check for a curses library, and if it needs termcap
diff --git a/configure.ac b/configure.ac
index f167804..334bf87 100644
--- a/configure.ac
+++ b/configure.ac
@@ -70,12 +70,20 @@ if test "x$coda_timespec" != xyes ; then
 fi
 
 dnl Make sure we configure any sub-projects before checking with pkg-config
+dnl GAH -- this now fails because PKG_CONFIG_PATH is re-exported with its initial value,
+dnl not the one we cooked up via the subdirs
+echo "PKG_CONFIG_PATH (1) is $PKG_CONFIG_PATH" 1>&2
 test -f "${srcdir}/lib-src/lwp/configure.ac" && AC_CONFIG_SUBDIRS([lib-src/lwp])
+CODA_CONFIG_PKG_SUBDIRS
 test -f "${srcdir}/lib-src/rpc2/configure.ac" && AC_CONFIG_SUBDIRS([lib-src/rpc2])
+CODA_CONFIG_PKG_SUBDIRS
 test -f "${srcdir}/lib-src/rvm/configure.ac" && AC_CONFIG_SUBDIRS([lib-src/rvm])
+CODA_CONFIG_PKG_SUBDIRS
+
 CODA_CONFIG_SUBDIRS
 
 dnl pkg-config stuff
+echo "PKG_CONFIG_PATH (2) is $PKG_CONFIG_PATH" 1>&2
 PKG_CHECK_MODULES([RVM_RPC2], [rvmlwp rpc2])
 PKG_CHECK_MODULES([LWP], [lwp >= 2.11])
 PKG_CHECK_MODULES([RPC2], [rpc2 >= 2.20])
```

**Comment by jaharkes** [comment]
Yeah, I looked into this last night and it all came flooding back. There was some strong language that I probably should not add as comments, but more comments in this area are definitely useful.

The `test -z "$PKG_CONFIG_PATH"` bit is only a workaround so that when we override the path, we still look in the normal places, I guess at the time I didn't find a reliable way to extract the default path and it could be any of `/usr/{,local/}lib{,64}/pkgconfig`, and possibly others so I probably assumed ${libdir}/pkgconfig most likely matched the current default.

The problem with having PKG_CONFIG_PATH already in the environment is that it is getting picked up really early on by autoconf as one of the `ac_precious_vars` which is then turned into the `ac_args` list that is passed down as we configure subprojects. It is picked up so early that we can't override it, and there are probably too many internal autoconf variables to change it later on.

I'm going to try to not rely on passing a modified PKG_CONFIG_PATH down to the rpc2 and rvm subprojects, but have them do their own discovery by looking if they are located adjacent to the lwp source tree (i.e. test for $(top_srcdir)/../lwp/). Then we only have to make sure subproject configure is completed before we try to do the pkgconfig lookups in the main configure, I think.

**Comment by danielrobbins** [comment]
@jaharkes you're welcome. I am still a bit uncomfortable with Gentoo pre-setting PKG_CONFIG_PATH as I think it's unnecessary, but it is probably best if coda will build whether it is set already or not. 

I'm excited to play more with coda and I'll continue to report any issues I find here.
