### ISSUE TITLE
Find the latest version of the Coda documentation source

### ISSUE THREAD

**Issue by jaharkes** [cmusatyalab/coda#14]
There are quite a few cases where source and documentation have diverged, but I'm not sure where the latest version of the documentation is. ISTR we converted everything to Docbook XML at some point, but have only located CVS repos and checkouts with older Linuxdoc SGML documentation source.
- [ ] Fix incorrect information in Coda Howto (#4, #10)
- [ ] Document codasrv -d option (#5)

**Comment by krichter722** [comment]
Any progress on this? During a re-attempt of setting up coda on Ubuntu 17.04 I noticed that [the howto](http://www.coda.cs.cmu.edu/doc/html/coda-howto.html) still contains issues like mentioning non-existing `venus-setup`.

**Comment by jaharkes** [comment]
I pushed whatever I could find as the most recent version to a new repository https://github.com/cmusatyalab/coda-doc/

I managed to build everything after installing the linuxdoc-tools, linuxdoc-tools-latex, and linuxdoc-tools-text packages on a Debian-jessie system.

**Comment by krichter722** [comment]
> I pushed whatever I could find as the most recent version to a new repository https://github.com/cmusatyalab/coda-doc/

Thank you. The `coda-doc` project doesn't install any files except for the projects `README` (I used `checkinstall` for the installation, so I'm getting a list of files which have been installed). If the project contains better information than the quite outdated Howto, it'd be nice to focus on, otherwise, I recommend updating the Howto. I'm trying to get coda running for almost a year now (with interruptions; I understand that it's not stable yet, etc.), and it'd be nice to have a reference to orientate on and file better issue reports.

**Comment by jaharkes** [comment]
With help from @aytchell the man pages in coda-doc are now updated to match what we have in coda-src, I think for now this is probably the best we can find, closing this issue.
