### ISSUE TITLE
coda-client-setup fails due to "line 176: [: char-major-67-*: binary operator expected"

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#18]
`sudo coda-client-setup richtercloud.de` fails due to `/usr/local/sbin/coda-client-setup: line 176: [: char-major-67-*: binary operator expected`.

There's [a thread on the mailing list](http://www.coda.cs.cmu.edu/maillists/codalist/codalist-2014/9300.html) which tries to figure out the reason for the issue and links bug reports about packaging in Redhat.

experienced with coda-6.9.9

**Comment by jaharkes** [comment]
I'm pretty sure coda-client-setup has not been tested on Debian and Ubuntu, it sets configuration paths that are not compliant with the linux filesystem standard. Updates module loading configuration that predate devfs and is not relevant.

It also may rely on running with bash instead of dsh/dash which seems to be the default /bin/sh on Ubuntu. Just a few of the many reasons why the packages replace coda-client-setup with dpkg-reconfigure coda-client.

**Comment by krichter722** [comment]
> I'm pretty sure coda-client-setup has not been tested on Debian and Ubuntu, it sets configuration paths that are not compliant with the linux filesystem standard. Updates module loading configuration that predate devfs and is not relevant.

> It also may rely on running with bash instead of dsh/dash which seems to be the default /bin/sh on Ubuntu. Just a few of the many reasons why the packages replace coda-client-setup with dpkg-reconfigure coda-client.

Then, I propose to make the script fail verbosely on non-supported systems (if parts are used by `dpkg` add an option).

How to run the script when installing from source on Ubuntu? It'd be strange and complicated if one had to package from source before being able to use it. It's "only" 200 lines. Maybe you can review it - and if you're on it take a look at portability issues, like `[ X$OS = XLinux ] ;` which should be `[ "X$OS" = "XLinux" ] ;` - those are likely the reason for the script failure.

**Comment by jaharkes** [comment]
The X$OS is fine, because when $OS is undefined it will still be 'X'. The failure was at a specific line, 176, and that is a part of the script that is setting up configs for the kernel autoloader on a static dev, which was inherently racy and has been replaced by devfs, udev, and I guess now systemd.

I queued up a patch that modernizes the file paths and removes the ancient devfs/static dev parts, but it is mixed up with some unrelated changes at the moment.
