### ISSUE TITLE
systemd unit installed by "make install" refers to wrong installation prefix

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#19]
After installing from source with `./bootstrap.sh && ./configure && make && make install` a `systemd` unit `/lib/systemd/system/coda-client.service` is created with `ExecStart=/usr/sbin/venus` whereas `venus` has been installed into `/usr/local/sbin`.

I figured out that `/lib/systemd/system/coda-client.service` is created by `sudo make install` by wrapping it in `checkinstall` and viewing installed files in the package manager `synaptic`.

experienced with coda-6.9.9

**Comment by jaharkes** [comment]
Not sure if that is that easy to fix because configure doesn't give nice paths, but for something like `@sbindir@` it returns `${exec_prefix}`, which in turn expands to `${prefix}/sbin`, etc. The systemd service file also assume fixed locations of things like the pid file, which really depends on how the client is configured. The default 'build from source' setup uses /usr/coda/... or /usr/local/coda/... for persistent memory/cache files so that it is easy to quickly wipe an installed version from a system.

But packaged releases adhere to distribution policy on file layout, so they use things like /var/run/coda-client.pid (/run?) etc. the systemd service scripts came from the fedora packaging, so it made sense in that context to use the distribution style paths instead of developer style.

Maybe the easiest approach is to not install systemd unit files unless explicitly requested with a configure flag.

**Comment by bgilbert** [comment]
You can avoid the problem of multiple layers of expansion by generating the unit file from Makefile.am, using Make variables and sed, instead of using `AC_CONFIG_FILES`.

**Comment by jaharkes** [comment]
That still doesn't solve the location of the pid files, which are not compile time, but local config specific. But they are 'hardcoded' in the systemd unit files.

**Comment by bgilbert** [comment]
The unit files should presumably match the default config, which could itself be populated from `localstatedir` etc.

A better fix for the pidfiles is not to have any (see #5), and to keep the daemons in the foreground when running from systemd.
