### ISSUE TITLE
deb package coda-backup conflicts with openafs-client because of /usr/share/man/man8/backup.8.gz

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#2]
The name `backup` for the manpage (and I assume the binary as well) seems troublesome.

experienced with 6.9.6-2+ubuntu16.04 on Ubuntu 16.04

**Comment by jaharkes** [comment]
This was expected because both OpenAFS and Coda are both forks of the same AFS codebase.

Here at CMU we haven't actually used `backup` in a long time and so we normally don't even bother installing it. We have successfully used `Amanda` to back up the 'voldump' output from `volutil dump`, and we have for a long time used `BackupPC`, with a script that wrapped `volutil dump | codadump2tar`.

I guess these could be renamed to `codabackup`, but it seems odd to just randomly stick 'coda' in front of every binary name.

**Comment by jaharkes** [comment]
Thought about this and it seems to me the best solution at this point would be to remove Coda's high-level backup tools (backup, tape.pl, etc.) and leave the low level stuff (volutil dump, codadump2tar).

The reasoning being, we don't use the high level tools ourselves so any bugs in the code are most likely not discovered until someone tries to use them to back up (or worse, restore) precious data and it fails.
