### ISSUE TITLE
vice-setup doesn't allow correction of invalid admin user UID

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#3]
Entering characters at the `Enter the uid of this user: ` causes them to be fail the UID setting with

    Not a valid user-id (it needs to be > 0).
    Owner must be a valid username/id, [entered characters] not found!

but the script proceeds. It's unclear what's the consequence of the invalid UID, i.e. whether the UID setting can be skipped or not. Anyway it's preferrable to enforce entering a UID in a loop until input is valid.

experienced with 6.9.6-2+ubuntu16.04 on Ubuntu 16.04

**Comment by jaharkes** [comment]
In the long run I'd like to get rid of the UID requirement, as I see it as a needlessly exposed implementation detail. UID's don't map right because we can in principle access a Coda realm from anywhere and the UID space is not globally unique. If we kept the user id's hidden and exposed name@realm, then a client could in theory create a local name->uid mapping dynamically and expose it to libc using applications using an LDAP-like server (or something else NSS can talk to). I guess this is sort of unrelated to this bugreport though.

The setup scripts are not robust in other areas either, I feel like it is not worth the effort to fix things here because setup is so infrequently used. Then again it is the 'first impression' for many users.

**Comment by jaharkes** [comment]
Not sure why this didn't retry for you because the script `vice-setup-user` actually clears the 'userid' local variable and should loop until that 'userid' variable has a value.

**Comment by jaharkes** [comment]
Ah, my bad. It doesn't test if the uid is numeric, somehow missed that the error messages you quoted were different from the ones in the 'Enter the uid of this user' loop.
