### ISSUE TITLE
Increase systemd unit timeouts

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#34]
Some units like `coda-client.service` sometimes require more than a minute to start (they seem to sometimes run `-init`, sometimes not, judging from the logs (documentation requested at #14)) and are then killed by `systemd` which might cause corruption leading to #33 and others.

experienced with 6.11.2-1+ubuntu16.10 on Ubuntu 16.10

**Comment by jaharkes** [comment]
Not sure why systemd even bothers to kill processes that take longer to fork. It clearly knows the child is still running and can probably tell that it is not a crashed process, but is actually using CPU and performing I/O.

We do long running tasks like RVM setup and initialization and doing a consistency check on the cached files on the client (just checking if for every file that is on disk we have a corresponding RVM entry and vv.) . And a little more involved check for all files in all volumes on the server.

These tasks are performed before the client and server fork into the background and start 'servicing' requests. And because it totally depends on number of cached/stored files, disk I/O bandwidth, available memory and how many other processes are starting up at the same time it is pretty hard to impossible to predict if or what the upper bound of such a timeout should be.

This hit me on my larger production servers as well, sometimes they would never come back up after a machine reboot, and that turned out to be systemd killing them before they were ready. I thought I had created an issue/patch for this, but I don't see either of that now.
