### ISSUE TITLE
Improve feedback after too large values for cacheblocks

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#35]
Large values for `cacheblocks` in `venus.conf` like `1000000000` or `500000000` cause `Recov_InitRDS: rds_zap_heap failed (RVM_ENOT_MAPPED)` during `venus -init`. No matter whether this is connected to the value or not the feedback should be improved explaining verbosely what the problem and possible fixes are. 10000000 works without problems.

experienced with 6.11.2-1+ubuntu16.10 on Ubuntu 16.10

**Comment by jaharkes** [comment]
if you specify cachefiles you can do whatever you like for cache blocks. The problem is a bit more complex, and not necessarily easily identified.

RVM itself could have failed because it didn't find a large enough address range to mmap the data file, or because the data file was too large for the available disk, or various other reasons. It just reports that it couldn't map the segment. Maybe 500M cache blocks would work for someone who happens to have 256GB of memory in their system, I don't know how much RVM it is trying to allocate here.

OTOH someone might not actually like to have that much memory reserved for files that will most likely never get cached on this client. Also this seems somewhat related to #37.

**Comment by jaharkes** [comment]
New cachesize option with a better file/blocks ratio calculation went into Coda-6.15 that should make this mostly irrelevant.
