### ISSUE TITLE
Current status and roadmap

### ISSUE THREAD

**Issue by anatoli26** [cmusatyalab/coda#55]
Hi,

I discovered Coda some years ago, at that time the project appeared to be semi-abandoned. Now I see there's some progress, this repo gets updates.

What is the current state of the project? Is Coda production-ready? If not, what are the main issues that should be solved? What core functionality is not working?

Also, I'd like to know who is maintaining the project and what are the plans for the future? Is there a roadmap?

Thanks!

**Comment by jaharkes** [comment]
We have been using Coda in production within our research group for longer than I've been with the group. (at least 20 years) Now that doesn't mean it is production-ready for whatever you might consider production, we just know from experience where the pitfalls are.

I am maintaining the project, although we occasionally have help from students or interns. Over the past couple of months Coda has been part of a larger project and so some of the activity you are seeing is from 3 areas where we are working on,

1. Wrapping a TCP tunnel around the UDP-based RPC2/SFTP communication protocol between clients and servers. This avoids many problems with firewalls some of which like to treat all UDP as DNS traffic and lose the port forwarding once 'the reply packet' has been passed back.
2. Provide an alternate way for applications to talk to the Coda client cache manager. Reason for this is that not all distributions ship with a Coda kernel module, and with secure boot and module signing it may not even be feasible to build your own. Also several systems have lost their Coda kernel modules over time (Solaris/MacOS/FreeBSD). So we started looking at a possible FUSE or 9PFS based approach. Right now it is still quite slow (1hr Coda compile) and incomplete (no authentication/cfs commands), but it is starting to look like it may become an usable alternative.
3. Streaming access to (large) files. We aren't actually trying to solve the 32-bit filesize limit in Coda, ideally 4GB but I'm not sure we've eliminated signed integers everywhere yet. But even with a several hundred MB file, access can be slow because we need to fetch the entire file before open can return a valid file descriptor. This is partly by design, whole file caching makes a lot of things easier, and partly for performance reasons, once a file is opened we allow direct access by the kernel without having to block for any missing pieces. On the other hand, Windows (and possibly other graphically oriented file browsers) like to open files and read a bit of metadata or icons as it tries to show a folder, and it ends up blocking until all the file data is retrieved. Or when you want to play video or music you don't (always) want to sit there waiting until the complete video has been downloaded to your client.

There is not a real roadmap as such, there are some things scribbled down at https://github.com/cmusatyalab/coda/projects/1 and I have some not quite well-enough formed ideas about getting rid of optimistic server-server replication and using simpler horizontally scaled servers on top of a Rados or S3 data store to get scalability and high-availability.

**Comment by anatoli26** [comment]
Jan, thanks a lot for such a detailed reply. With "production" I mean that the basic functionality is working stable, with reasonable performance and there are no show-stopper issues.

I'm looking for some years for a solution to host user home folders on a server in such a way as to permit access to the files both from LAN and internet where users may lose connection or just stay offline for long periods. Their files should be accessible while offline and sync once they are connected to the server again.

I'm particularly interested in knowing how conflicts are managed in Coda. I've seen the old documentation at http://coda.cs.cmu.edu/doc/html/manual/x518.html, but I'm not sure it's up-to-date. Could you please let me know the current state of conflicts management?

Also, where should I start to setup everything from scratch (server and client) with no prior knowledge of Coda? Same as with the previous question, there's the documentation at the cmu website, but it appears to be last updated in 2000.
