### ISSUE TITLE
deb packages don't install auth2-master.service unit

### ISSUE THREAD

**Issue by krichter722** [cmusatyalab/coda#9]
Strangely I still see this in the `bash` auto-completion of `systemctl status`, but not in the list of installed files in `synaptic` and can't find it in `apt-file`. Starting `auth2` with `root` privileges works fine, but it'd be nice to have a dependency within the init manager.

`codasrv` isn't started neither.

experienced with 6.9.6-2+ubuntu16.04 on Ubuntu 16.04

**Comment by jaharkes** [comment]
I've just started adding systemd unit files, based on the ones that Fedora had added as out-of-tree patches, after the 6.9.6 release and it is giving some packaging issues on Ubuntu versions that are older than Xenial because those do not have the necessary debhelper scripts. So it is expected that 6.9.6 does not have unit files for auth2 and codasrv.

**Comment by jaharkes** [comment]
Should be fixed by the 6.9.7 release that is not announced, but has been tagged, built and released.
